In [1]:
import pandas as pd

In [2]:
path = 'data/mass_shooting_events_stanford_msa_release_06142016.csv'
mass_shooting = pd.read_csv(path)

In [3]:
mass_shooting

,CaseID,Title,Location,City,State,Latitude,Longitude,Number of Victim Fatalities,Total Number of Fatalities,Number of Victims Injured,...,History of Mental Illness - General,Data Source 1,Data Source 2,Data Source 3,Data Source 4,Data Source 5,Data Source 6,Data Source 7,Military Experience,Class
0,1.0,University of Texas at Austin,"Austin, Texas",Austin,Texas,30.198887,-97.844159,16.0,17.0,32.0,...,Yes,http://en.wikipedia.org/wiki/Charles_Whitman,"Lexington Examiner (KY) - September 23, 2012",http://news.google.com/newspapers?id=lkk0AAAAI...,http://news.google.com/newspapers?id=PPUjAAAAI...,http://books.google.com/books?id=ClYEAAAAMBAJ&...,NaN,NaN,Yes,SPK
1,2.0,Rose-Mar College of Beauty,"Mesa, Arizona",Mesa,Arizona,33.422687,-111.816320,5.0,5.0,1.0,...,Yes,"""Slaughter In The College Of Beauty."" Time 88....",Section: Lexington True Crime Examiner,http://www.nydailynews.com/news/crime/beauty-s...,http://books.google.com/books?id=Cre7qsswRiwC&...,NaN,NaN,NaN,Unknown,MS
2,3.0,New Orleans Police Shootings,"New Orleans, Louisiana",New Orleans,Louisiana,30.068724,-89.931474,9.0,10.0,13.0,...,Yes,http://news.google.com/newspapers?nid=1144&dat...,http://theadvocate.com/home/4828836-125/rampag...,http://www.trutv.com/library/crime/notorious_m...,http://books.google.com/books?id=TfEDmROcZwEC&...,NaN,NaN,NaN,Unknown,SPK
3,4.0,Clara Barton Elementary School,"Chicago, Illinois",Chicago,Illinois,41.839280,-87.688181,1.0,1.0,3.0,...,Yes,http://news.google.com/newspapers?nid=1338&dat...,http://news.google.com/newspapers?nid=1144&dat...,http://www.leagle.com/xmlResult.aspx?page=1&xm...,NaN,NaN,NaN,NaN,Unknown,MS
4,5.0,Olean High School,"Olean, New York",Olean,New York,42.081854,-78.432139,3.0,3.0,7.0,...,No,http://buffalo.ynn.com/content/top_stories/622...,School Shootings: a History Part One of a seri...,http://www.newswithviews.com/Erica/Carle10.htm,http://books.google.com/books?id=ZuKoSskEWyIC&...,"""Olean High School Shooting"". Larrie Benton Za...",NaN,NaN,Unknown,MS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
342,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
343,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
344,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
345,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
346,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
mass_shooting.columns

Index(['CaseID', 'Title', 'Location', 'City', 'State', 'Latitude', 'Longitude',
       'Number of Victim Fatalities', 'Total Number of Fatalities',
       'Number of Victims Injured', 'Total Number of Victims', 'Description',
       'Date', 'Day of Week', 'Date - Detailed', 'Shooter Name',
       'Shooter Age(s)', 'Average Shooter Age', 'Shooter Sex', 'Shooter Race',
       'Type of Gun - Detailed', 'Type of Gun - General', 'Number of Shotguns',
       'Number of Rifles', 'Number of Handguns', 'Total Number of Guns',
       'Number of Automatic Guns', 'Number of Semi-Automatic Guns',
       'Fate of Shooter at the scene', 'Shooter's Cause of Death',
       'School Related', 'Place Type', 'Relationship to Incident Location',
       'Targeted Victim/s - Detailed', 'Targeted Victim/s - General',
       'Possible Motive - Detailed', 'Possible Motive - General',
       'History of Mental Illness - Detailed',
       'History of Mental Illness - General', 'Data Source 1', 'Data Source 2',
       'Data Source 3', 'Data Source 4', 'Data Source 5', 'Data Source 6',
       'Data Source 7', 'Military Experience', 'Class'],
      dtype='object')

In [5]:
mass_shooting_revised = mass_shooting.drop(['Title', 'Location', 'Total Number of Fatalities',
    'Description',
    'Day of Week', 'Date - Detailed', 'Shooter Name',
       'Average Shooter Age',
       'Type of Gun - Detailed', 'Number of Shotguns',
       'Number of Rifles', 'Number of Handguns',
       'Number of Automatic Guns', 'Number of Semi-Automatic Guns',
       'Fate of Shooter at the scene',
       'School Related',
       'Targeted Victim/s - Detailed',
       'Possible Motive - Detailed',
       'History of Mental Illness - Detailed',
       'Data Source 1', 'Data Source 2',
       'Data Source 3', 'Data Source 4', 'Data Source 5', 'Data Source 6',
       'Data Source 7', 'Class'], axis = 1)

In [6]:
mass_shooting_revised

,CaseID,City,State,Latitude,Longitude,Number of Victim Fatalities,Number of Victims Injured,Total Number of Victims,Date,Shooter Age(s),...,Shooter Race,Type of Gun - General,Total Number of Guns,Shooter's Cause of Death,Place Type,Relationship to Incident Location,Targeted Victim/s - General,Possible Motive - General,History of Mental Illness - General,Military Experience
0,1.0,Austin,Texas,30.198887,-97.844159,16.0,32.0,48.0,8/1/1966,25,...,White American or European American,Multiple guns,7,Killed,College/University/Adult education,Place of schooling,General public,Mental illness,Yes,Yes
1,2.0,Mesa,Arizona,33.422687,-111.816320,5.0,1.0,6.0,11/12/1966,18,...,White American or European American,Handgun,1,Not applicable,College/University/Adult education,None,Students/Classmates/Teacher,Mental illness,Yes,Unknown
2,3.0,New Orleans,Louisiana,30.068724,-89.931474,9.0,13.0,22.0,12/31/72,23,...,Black American or African American,Multiple guns,2,Killed,Government facility,Local government,Government,Race,Yes,Unknown
3,4.0,Chicago,Illinois,41.839280,-87.688181,1.0,3.0,4.0,1/17/74,14,...,Unknown,Handgun,2,Not applicable,Primary school,Place of schooling,Students/Classmates/Teacher,Expulsion/Suspension,Yes,Unknown
4,5.0,Olean,New York,42.081854,-78.432139,3.0,7.0,10.0,12/30/74,17,...,White American or European American,Multiple guns,2,Not applicable,Secondary school,Place of schooling,General public,Mental illness,No,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
342,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
343,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
344,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
345,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
346,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
mass_shooting_refined = mass_shooting_revised[['CaseID','City', 'State', 'Latitude', 'Longitude',
       'Number of Victim Fatalities',
       'Number of Victims Injured', 'Total Number of Victims',
       'Date',
       'Shooter Age(s)', 'Shooter Sex', 'Shooter Race',
       'Type of Gun - General','Total Number of Guns',"Shooter's Cause of Death",
       'Place Type', 'Relationship to Incident Location',
       'Targeted Victim/s - General','Possible Motive - General',
       'History of Mental Illness - General', 'Military Experience']]

In [9]:
mass_shooting_refined

,CaseID,City,State,Latitude,Longitude,Number of Victim Fatalities,Number of Victims Injured,Total Number of Victims,Date,Shooter Age(s),...,Shooter Race,Type of Gun - General,Total Number of Guns,Shooter's Cause of Death,Place Type,Relationship to Incident Location,Targeted Victim/s - General,Possible Motive - General,History of Mental Illness - General,Military Experience
0,1.0,Austin,Texas,30.198887,-97.844159,16.0,32.0,48.0,8/1/1966,25,...,White American or European American,Multiple guns,7,Killed,College/University/Adult education,Place of schooling,General public,Mental illness,Yes,Yes
1,2.0,Mesa,Arizona,33.422687,-111.816320,5.0,1.0,6.0,11/12/1966,18,...,White American or European American,Handgun,1,Not applicable,College/University/Adult education,None,Students/Classmates/Teacher,Mental illness,Yes,Unknown
2,3.0,New Orleans,Louisiana,30.068724,-89.931474,9.0,13.0,22.0,12/31/72,23,...,Black American or African American,Multiple guns,2,Killed,Government facility,Local government,Government,Race,Yes,Unknown
3,4.0,Chicago,Illinois,41.839280,-87.688181,1.0,3.0,4.0,1/17/74,14,...,Unknown,Handgun,2,Not applicable,Primary school,Place of schooling,Students/Classmates/Teacher,Expulsion/Suspension,Yes,Unknown
4,5.0,Olean,New York,42.081854,-78.432139,3.0,7.0,10.0,12/30/74,17,...,White American or European American,Multiple guns,2,Not applicable,Secondary school,Place of schooling,General public,Mental illness,No,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
342,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
343,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
344,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
345,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
346,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
clean_df = mass_shooting_refined.dropna(how='all')

In [11]:
clean_df

,CaseID,City,State,Latitude,Longitude,Number of Victim Fatalities,Number of Victims Injured,Total Number of Victims,Date,Shooter Age(s),...,Shooter Race,Type of Gun - General,Total Number of Guns,Shooter's Cause of Death,Place Type,Relationship to Incident Location,Targeted Victim/s - General,Possible Motive - General,History of Mental Illness - General,Military Experience
0,1.0,Austin,Texas,30.198887,-97.844159,16.0,32.0,48.0,8/1/1966,25,...,White American or European American,Multiple guns,7,Killed,College/University/Adult education,Place of schooling,General public,Mental illness,Yes,Yes
1,2.0,Mesa,Arizona,33.422687,-111.816320,5.0,1.0,6.0,11/12/1966,18,...,White American or European American,Handgun,1,Not applicable,College/University/Adult education,None,Students/Classmates/Teacher,Mental illness,Yes,Unknown
2,3.0,New Orleans,Louisiana,30.068724,-89.931474,9.0,13.0,22.0,12/31/72,23,...,Black American or African American,Multiple guns,2,Killed,Government facility,Local government,Government,Race,Yes,Unknown
3,4.0,Chicago,Illinois,41.839280,-87.688181,1.0,3.0,4.0,1/17/74,14,...,Unknown,Handgun,2,Not applicable,Primary school,Place of schooling,Students/Classmates/Teacher,Expulsion/Suspension,Yes,Unknown
4,5.0,Olean,New York,42.081854,-78.432139,3.0,7.0,10.0,12/30/74,17,...,White American or European American,Multiple guns,2,Not applicable,Secondary school,Place of schooling,General public,Mental illness,No,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302,312.0,Brooksville,Alabama,34.162040,-86.475543,0.0,4.0,4.0,4/19/16,38,...,White American or European American,Multiple guns,2,Killed,Street/Highway,Unknown,General Public,Unknown,Yes,Unknown
303,313.0,Baltimore,Maryland,39.290385,-76.612189,0.0,4.0,4.0,4/21/16,20,...,Black American or African American,handgun,1,Not Applicable,Residential Home/Neighborhood,Unknown,Social,Social Dispute,Unknown,Unknown
304,314.0,Halifax,Virginia,36.765971,-78.928344,0.0,6.0,6.0,4/24/16,50,...,Black American or African American,Unknown,Unknown,Suicide,Residential home/Neighborhood,Place of residency,Family,Domestic Dispute,Unknown,NaN
305,315.0,Forestville,Maryland,38.845113,-76.874972,1.0,4.0,5.0,4/26/16,Unknown,...,Unknown,Unknown,Unknown,Not Applicable,Street/Highway,Unknown,Unknown,Unknown,Unknown,Unknown
306,316.0,Ferguson,Missouri,38.744217,-90.305391,0.0,4.0,4.0,4/29/16,Unknown,...,Unknown,Unknown,Unknown,Not Applicable,Residential home/Neighborhood,Unknown,Unknown,Social Dispute,Unknown,Unknown

In [12]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 307 entries, 0 to 306
Data columns (total 21 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   CaseID                               307 non-null    float64
 1   City                                 307 non-null    object
 2   State                                307 non-null    object
 3   Latitude                             307 non-null    float64
 4   Longitude                            307 non-null    float64
 5   Number of Victim Fatalities          307 non-null    float64
 6   Number of Victims Injured            307 non-null    float64
 7   Total Number of Victims              307 non-null    float64
 8   Date                                 307 non-null    object
 9   Shooter Age(s)                       307 non-null    object
 10  Shooter Sex                          307 non-null    object
 11  Shooter Race                         307 non-null    object
 12  Type of Gun - General                307 non-null    object
 13  Total Number of Guns                 307 non-null    object
 14  Shooter's Cause of Death             307 non-null    object
 15  Place Type                           307 non-null    object
 16  Relationship to Incident Location    306 non-null    object
 17  Targeted Victim/s - General          306 non-null    object
 18  Possible Motive - General            306 non-null    object
 19  History of Mental Illness - General  307 non-null    object
 20  Military Experience                  301 non-null    object
dtypes: float64(6), object(15)
memory usage: 52.8+ KB

In [13]:
# clean_df['Shooter Age(s)'] = clean_df['Shooter Age(s)'].replace({'Unknown':0})
clean_df.columns

Index(['CaseID', 'City', 'State', 'Latitude', 'Longitude',
       'Number of Victim Fatalities', 'Number of Victims Injured',
       'Total Number of Victims', 'Date', 'Shooter Age(s)', 'Shooter Sex',
       'Shooter Race', 'Type of Gun - General', 'Total Number of Guns',
       'Shooter's Cause of Death', 'Place Type',
       'Relationship to Incident Location', 'Targeted Victim/s - General',
       'Possible Motive - General', 'History of Mental Illness - General',
       'Military Experience'],
      dtype='object')

In [14]:
# clean_df.loc[clean_df['Shooter Age(s)'] == 'Unknown', 'Shooter Age(s)'] = 0
clean_df = 

clean_df.loc[clean_df['Total Number of Guns'] == 'Unknown', 'Total Number of Guns'] = 0

clean_df

/Users/saheedosoba/opt/anaconda3/lib/python3.9/site-packages/pandas/core/indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

,CaseID,City,State,Latitude,Longitude,Number of Victim Fatalities,Number of Victims Injured,Total Number of Victims,Date,Shooter Age(s),...,Shooter Race,Type of Gun - General,Total Number of Guns,Shooter's Cause of Death,Place Type,Relationship to Incident Location,Targeted Victim/s - General,Possible Motive - General,History of Mental Illness - General,Military Experience
0,1.0,Austin,Texas,30.198887,-97.844159,16.0,32.0,48.0,8/1/1966,25,...,White American or European American,Multiple guns,7,Killed,College/University/Adult education,Place of schooling,General public,Mental illness,Yes,Yes
1,2.0,Mesa,Arizona,33.422687,-111.816320,5.0,1.0,6.0,11/12/1966,18,...,White American or European American,Handgun,1,Not applicable,College/University/Adult education,None,Students/Classmates/Teacher,Mental illness,Yes,Unknown
2,3.0,New Orleans,Louisiana,30.068724,-89.931474,9.0,13.0,22.0,12/31/72,23,...,Black American or African American,Multiple guns,2,Killed,Government facility,Local government,Government,Race,Yes,Unknown
3,4.0,Chicago,Illinois,41.839280,-87.688181,1.0,3.0,4.0,1/17/74,14,...,Unknown,Handgun,2,Not applicable,Primary school,Place of schooling,Students/Classmates/Teacher,Expulsion/Suspension,Yes,Unknown
4,5.0,Olean,New York,42.081854,-78.432139,3.0,7.0,10.0,12/30/74,17,...,White American or European American,Multiple guns,2,Not applicable,Secondary school,Place of schooling,General public,Mental illness,No,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302,312.0,Brooksville,Alabama,34.162040,-86.475543,0.0,4.0,4.0,4/19/16,38,...,White American or European American,Multiple guns,2,Killed,Street/Highway,Unknown,General Public,Unknown,Yes,Unknown
303,313.0,Baltimore,Maryland,39.290385,-76.612189,0.0,4.0,4.0,4/21/16,20,...,Black American or African American,handgun,1,Not Applicable,Residential Home/Neighborhood,Unknown,Social,Social Dispute,Unknown,Unknown
304,314.0,Halifax,Virginia,36.765971,-78.928344,0.0,6.0,6.0,4/24/16,50,...,Black American or African American,Unknown,0,Suicide,Residential home/Neighborhood,Place of residency,Family,Domestic Dispute,Unknown,NaN
305,315.0,Forestville,Maryland,38.845113,-76.874972,1.0,4.0,5.0,4/26/16,Unknown,...,Unknown,Unknown,0,Not Applicable,Street/Highway,Unknown,Unknown,Unknown,Unknown,Unknown
306,316.0,Ferguson,Missouri,38.744217,-90.305391,0.0,4.0,4.0,4/29/16,Unknown,...,Unknown,Unknown,0,Not Applicable,Residential home/Neighborhood,Unknown,Unknown,Social Dispute,Unknown,Unknown

In [15]:
clean_df.rename(columns = {'CaseID':'case_id','City':'city', 'State':'state', 'Latitude':'latitude', 'Longitude':'longitude',
       'Number of Victim Fatalities':'number_of_victim_fatalities',
       'Number of Victims Injured': 'number_of_victims_injured', 'Total Number of Victims':'total_number_of_victims',
       'Date':'date',
       'Shooter Age(s)':'shooter_age(s)', 'Shooter Sex':'shooter_sex', 'Shooter Race':'shooter_race',
       'Type of Gun - General':'type_of_gun','Total Number of Guns':'total_number_of_guns',"Shooter's Cause of Death":'shooter_cause_of_death',
       'Place Type': 'place_type', 'Relationship to Incident Location':'relationship_to_incident_location',
       'Targeted Victim/s - General':'targeted_victims','Possible Motive - General':'possible_motive',
       'History of Mental Illness - General':'history_of_mental_illness', 'Military Experience':'military_experience'}, inplace = True)

/Users/saheedosoba/opt/anaconda3/lib/python3.9/site-packages/pandas/core/frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

In [16]:
clean_df['date'] = pd.to_datetime(clean_df['date'])
clean_df['total_number_of_guns'] = pd.to_numeric(clean_df['total_number_of_guns'])

/var/folders/df/2jw1cn_d69j23pvjc1whb2ym0000gn/T/ipykernel_68384/2794638423.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_df['date'] = pd.to_datetime(clean_df['date'])
/var/folders/df/2jw1cn_d69j23pvjc1whb2ym0000gn/T/ipykernel_68384/2794638423.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_df['total_number_of_guns'] = pd.to_numeric(clean_df['total_number_of_guns'])

In [17]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 307 entries, 0 to 306
Data columns (total 21 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   CaseID                             307 non-null    float64
 1   city                               307 non-null    object
 2   state                              307 non-null    object
 3   latitude                           307 non-null    float64
 4   longitude                          307 non-null    float64
 5   number_of_victim_fatalities        307 non-null    float64
 6   number_of_victims_injured          307 non-null    float64
 7   total_number_of_victims            307 non-null    float64
 8   date                               307 non-null    datetime64[ns]
 9   shooter_age(s)                     307 non-null    object
 10  shooter_sex                        307 non-null    object
 11  shooter_race                       307 non-null    object
 12  type_of_gun                        307 non-null    object
 13  total_number_of_guns               307 non-null    int64
 14  shooter_cause_of_death             307 non-null    object
 15  place_type                         307 non-null    object
 16  relationship_to_incident_location  306 non-null    object
 17  targeted_victims                   306 non-null    object
 18  possible_motive                    306 non-null    object
 19  history_of_mental_illness          307 non-null    object
 20  military_experience                301 non-null    object
dtypes: datetime64[ns](1), float64(6), int64(1), object(13)
memory usage: 52.8+ KB

In [18]:
clean_df

,CaseID,city,state,latitude,longitude,number_of_victim_fatalities,number_of_victims_injured,total_number_of_victims,date,shooter_age(s),...,shooter_race,type_of_gun,total_number_of_guns,shooter_cause_of_death,place_type,relationship_to_incident_location,targeted_victims,possible_motive,history_of_mental_illness,military_experience
0,1.0,Austin,Texas,30.198887,-97.844159,16.0,32.0,48.0,1966-08-01,25,...,White American or European American,Multiple guns,7,Killed,College/University/Adult education,Place of schooling,General public,Mental illness,Yes,Yes
1,2.0,Mesa,Arizona,33.422687,-111.816320,5.0,1.0,6.0,1966-11-12,18,...,White American or European American,Handgun,1,Not applicable,College/University/Adult education,None,Students/Classmates/Teacher,Mental illness,Yes,Unknown
2,3.0,New Orleans,Louisiana,30.068724,-89.931474,9.0,13.0,22.0,2072-12-31,23,...,Black American or African American,Multiple guns,2,Killed,Government facility,Local government,Government,Race,Yes,Unknown
3,4.0,Chicago,Illinois,41.839280,-87.688181,1.0,3.0,4.0,1974-01-17,14,...,Unknown,Handgun,2,Not applicable,Primary school,Place of schooling,Students/Classmates/Teacher,Expulsion/Suspension,Yes,Unknown
4,5.0,Olean,New York,42.081854,-78.432139,3.0,7.0,10.0,1974-12-30,17,...,White American or European American,Multiple guns,2,Not applicable,Secondary school,Place of schooling,General public,Mental illness,No,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302,312.0,Brooksville,Alabama,34.162040,-86.475543,0.0,4.0,4.0,2016-04-19,38,...,White American or European American,Multiple guns,2,Killed,Street/Highway,Unknown,General Public,Unknown,Yes,Unknown
303,313.0,Baltimore,Maryland,39.290385,-76.612189,0.0,4.0,4.0,2016-04-21,20,...,Black American or African American,handgun,1,Not Applicable,Residential Home/Neighborhood,Unknown,Social,Social Dispute,Unknown,Unknown
304,314.0,Halifax,Virginia,36.765971,-78.928344,0.0,6.0,6.0,2016-04-24,50,...,Black American or African American,Unknown,0,Suicide,Residential home/Neighborhood,Place of residency,Family,Domestic Dispute,Unknown,NaN
305,315.0,Forestville,Maryland,38.845113,-76.874972,1.0,4.0,5.0,2016-04-26,Unknown,...,Unknown,Unknown,0,Not Applicable,Street/Highway,Unknown,Unknown,Unknown,Unknown,Unknown
306,316.0,Ferguson,Missouri,38.744217,-90.305391,0.0,4.0,4.0,2016-04-29,Unknown,...,Unknown,Unknown,0,Not Applicable,Residential home/Neighborhood,Unknown,Unknown,Social Dispute,Unknown,Unknown

In [19]:
clean_df.to_csv('Data/revised_cleanDF.csv', index = False)